name: NCMDemo
options:
  bundleIdPrefix: com.ncmdemo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false

packages:
  NeteaseCloudMusicAPI:
    path: ..

targets:
  NCMDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: NeteaseCloudMusicAPI
    info:
      path: Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSExceptionDomains:
            music.126.net:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ncmdemo.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
